### ISSUE TITLE
Login via discord message

### ISSUE THREAD

**Issue by dgradecak** [DenisIndenbom/DiscordAuth#11]
Hi,

suddenly the plugin says that he user account does not exist, by that I mean inside of the MC client it says in red "Login via discord" and I only find this line for that problem
https://github.com/DenisIndenbom/DiscordAuth/blob/a4b4d382d28176610ee2d5c26b34bcb1fad54ab9/src/main/java/com/denisindenbom/discordauth/listeners/PlayerListener.java#L217C20-L218C101

the users were correctly added via !add ... but now for wahtever reason the login does nto work, even if the DM is well received and marked as answered to the Discord bot.

Any idea what this could potentially be?

I also deleted the db file and restarted, and recreated the container too ...  but nothing helps
Checked in the DB directly and the user exist with the right name and discord id

**Comment by dgradecak** [comment]
ok, I fixed it in the code ... strange but it was also the unicode on linux, will create a PR

**Comment by DenisIndenbom** [comment]
Yes, it is strange, but perhaps in our case it is logical.

Thank you for your help and interest in my plugin.
