### ISSUE TITLE
Add direct download on the Spigot page

### ISSUE THREAD

**Issue by NetworkReplicator** [DenisIndenbom/DiscordAuth#14]
I run a Minecraft server on the free server host [Aternos,](https://aternos.org) with my server being configured with Bedrock *(through Geyser)*, cracked *(through online mode being off)* & Premium user support, all at once.

Due to online mode being off, however, *anyone* may join with *any* username. I found this plugin to be a particularly convenient solution compared to other login plugins, which all mostly use passwords; but, due to the plugin's [Spigot page](https://www.spigotmc.org/resources/discordauth.104766/) not providing a download directly there, I cannot request it for suggestion on Aternos.

![image](https://github.com/DenisIndenbom/DiscordAuth/assets/85638488/7bcb3706-39a1-45f2-a64d-559c3fee0707)

This should be a simple fix for @DenisIndenbom, providing the plugin directly on spigotmc.org alongside GitHub releases, and would help other Aternos users looking for it in the future.

Cheers!
\- P

**Comment by DenisIndenbom** [comment]
Hi,

I added a [direct link](https://www.spigotmc.org/resources/discordauth.104766/update?update=537990) to the plugin file in the new update. I hope I helped u.

P.S: Spigot page cannot store this plugin, because it's too big (~10.74 MB).

Thank u for this issue!
