### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by 4equest** [DenisIndenbom/DiscordAuth#4]
I would like to have a setting to allow login only for players who have been granted a specific role in Discord.
Also, is it possible to make it unnecessary to authenticate via DM when logging in?
I only need the first registration.

**Comment by DenisIndenbom** [comment]
Hi!

First, you can allow only certain roles to write to the verification channel (the channel that the bot listens to).

Secondly, the vanilla minecraft client, as I know, does not allow you to save session keys, so you have to constantly confirm logging in to your account when you log in to the server. I may be wrong, but I do not know how to implement longer sessions.

**Comment by 4equest** [comment]
Thanks for the quick response.
I am using the translation by DeepL so it may be difficult to convey...

The reason we need to validate Discord roles is that some players will log in to the Minecraft server after leaving the Discord server.
Specifically, we would like to use the Discord role that is granted only to registered Youtube memberships for verification.

Secondly, I am not talking about a Minecraft login session, although I am talking about DMs at login.
In this plugin, the DMs are sent through Discord from the Discord BOT when logging into the Minecraft server.
I am asking for an option to disable the sending of this DM and add an option to log in automatically.

**Comment by DenisIndenbom** [comment]
I hope I understood you correctly this time. 

(1) It is rather a plugin error that it allows players to enter the server after they have left the discord server. I'll fix this stupid bug. 

(2) Does your server allow pirated minecraft clients to connect (`online-mode=false`)? Pirate clients can specify any nickname and therefore discord bot sends a confirmation request to log in to the account in private messages. If not, then I can implement the feature so that it does not send a confirm request to private messages if online-mode=true and the special parameter is also true.

**Comment by 4equest** [comment]
Thank you for dealing with this issue again.

(1) I was a little bad in the way I communicated.
I want to validate the roles that are automatically granted by joining a Youtube channel membership.
That, and the need to automatically regulate players who only enter the Discord server when they enter the Minecraft server.

(2) I am running a Minecraft server that is only open to the official version. 
It would be great if you could implement the feature.
But I think it would be better to manage by UUID instead of MCID, because the name changeable is the same for the official version.

Thank you very much.

**Comment by DenisIndenbom** [comment]
Ok, now I understand second point, but I don't understand first point again. What do you mean by automatically validate?

**Comment by 4equest** [comment]
I mean, to make it more flexible to manage.
I would like to have a role validation mechanism like the one in "DI Discord Login"(https://www.spigotmc.org/resources/di-discord-login.86672/).
( I stopped using this plugin due to its bugs and slow development...)
Forget about what I said before, please.

**Comment by DenisIndenbom** [comment]
Okay, I read about this plugin and watch one video in YouTube. There is generally a different registration mechanisms.

I will try to implement this feature, but it will take time.
