### ISSUE TITLE
Setting the session duration

### ISSUE THREAD

**Issue by MrWeez** [DenisIndenbom/DiscordAuth#5]
Good afternoon, I really liked your plugin, but there is a small suggestion. Add a setting to the plugin config responsible for the duration of the session, it would be convenient because players will not need to constantly confirm logging in to the server. Thank you in advance.

**Comment by DenisIndenbom** [comment]
Hello, is your server open only for official versions? (online-mod=true)

**Comment by DenisIndenbom** [comment]
Hello,
As far as I know, the session system cannot be implemented normally in minecraft because it is assumed that the client stores the session key (the vanilla minecraft client does not store the session key), and it is unsafe to use the player's IP address instead of the session key.

One of the ideas to solve the problem is to make a one-time login confirmation for official accounts, but this will only work on official servers. I am currently implementing this feature.

**Comment by MrWeez** [comment]
> Здравствуйте, насколько я знаю, сеансовая система не может быть реализована нормально в minecraft, потому что предполагается, что клиент хранит сеансовый ключ (ванильный клиент minecraft не хранит сеансовый ключ), и небезопасно использовать IP-адрес игрока вместо сеансового ключа.
> 
> Одна из идей для решения проблемы — сделать одноразовое подтверждение входа в систему для официальных аккаунтов, но это будет работать только на официальных серверах. В настоящее время я реализую эту функцию.

Thank you for the answer, but could you explain to me why it is unsafe to use IP? It's just the easiest and most guaranteed way to implement the idea of sessions.

**Comment by MrWeez** [comment]
> Hello, As far as I know, the session system cannot be implemented normally in minecraft because it is assumed that the client stores the session key (the vanilla minecraft client does not store the session key), and it is unsafe to use the player's IP address instead of the session key.
> 
> One of the ideas to solve the problem is to make a one-time login confirmation for official accounts, but this will only work on official servers. I am currently implementing this feature.

Thank you for the answer, but could you explain to me why it is unsafe to use IP? It's just the easiest and most guaranteed way to implement the idea of sessions.

**Comment by DenisIndenbom** [comment]
Binding a session to an IP address will not make it secure, because the server can see that many different users are using the same IP address for different reasons (one of them is proxy servers).

To find out more, it's better to Google "why it's not safe to use a user's IP address for sessions."
